"""gRPC Protobuf Stubs — Phase 2 (SCAFFOLD)

Generated from sandbox.proto.
TODO: Define .proto file, generate stubs, implement gRPC service.
"""

# Placeholder — will be generated by grpcio-tools from sandbox.proto
# message SandboxRequest { string sandbox_id = 1; string command = 2; }
# message SandboxResponse { string output = 1; bool done = 2; }
